name: Create release

on:
  push:
    tags:
      - '*.*.*'

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Extract release notes
        id: extract-release-notes
        uses: ffurrer2/extract-release-notes@v1

      - name: Create release
        uses: softprops/action-gh-release@v1
        with:
          body: ${{ steps.extract-release-notes.outputs.release_notes }}
          draft: false
          name: ${{ github.ref }}
          prerelease: false
          tag_name: ${{ github.ref }}
          token: ${{ secrets.WORKFLOWS_CREATE_RELEASE_TOKEN }}
